#!/bin/bash

cat << EOF


    _________   ______
   / ____/   | / ____/
  / __/ / /| |/ / __
 / /___/ ___ / /_/ /
/_____/_/  |_\____/



EOF

sleep 0.5

git clone "https://github.com/angadsharma1016/express-auth-generator.git"
read -p "Enter the name of your project: " name

if [ ${#name} = 0 ]
then
	  if [ $1 = "google" ]
    then
      mv express-auth-generator "default"
      cd default
      git checkout google_auth
      rm -rf .git
      cd ..
    elif [ $1 = "facebook" ]
    then
      mv express-auth-generator "default"
      cd default
      git checkout facebook_auth
      rm -rf .git
      cd ..
    else
      mv express-auth-generator "default"
      rm -rf ./default/.git
    fi

else
  if [ $1 = "google" ]
  then
    mv express-auth-generator $name
    cd $name
    git checkout google_auth
    rm -rf .git
    cd ..
  elif [ $1 = "facebook" ]
  then
    mv express-auth-generator $name
    cd $name
    git checkout facebook_auth
    rm -rf .git
    cd ..
  else
    mv express-auth-generator $name
    rm -rf ./$name/.git
  fi
fi
