#!/bin/bash


if [ $1 = "" ]
then
  echo "Welcome to useful-tabs"
elif [ $1 = "-g" ]
then
  echo "Opening github... "
  firefox www.github.com/$2/$3&
elif [ $1 = "-s" ]
then
  echo "Opening firefox and querying stackoverflow...."
  firefox https://stackoverflow.com/search?q=$2
fi
